/*
 * FINBOURNE Notifications API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Notifications.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Notifications.Sdk.Model
{
    /// <summary>
    /// The information required to create or update an AWS SQS notification
    /// </summary>
    [DataContract(Name = "AmazonSqsNotificationType")]
    public partial class AmazonSqsNotificationType : IEquatable<AmazonSqsNotificationType>, IValidatableObject
    {
        /// <summary>
        /// The type of delivery mechanism for this notification
        /// </summary>
        /// <value>The type of delivery mechanism for this notification</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum AmazonSqs for value: AmazonSqs
            /// </summary>
            [EnumMember(Value = "AmazonSqs")]
            AmazonSqs = 1
        }


        /// <summary>
        /// The type of delivery mechanism for this notification
        /// </summary>
        /// <value>The type of delivery mechanism for this notification</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AmazonSqsNotificationType" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AmazonSqsNotificationType() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AmazonSqsNotificationType" /> class.
        /// </summary>
        /// <param name="type">The type of delivery mechanism for this notification (required).</param>
        /// <param name="apiKeyRef">Reference to API key from Configuration Store (required).</param>
        /// <param name="apiSecretRef">Reference to API secret from Configuration Store (required).</param>
        /// <param name="body">The body of the Amazon Queue Message (required).</param>
        /// <param name="queueUrlRef">Reference to queue url from Configuration Store (required).</param>
        public AmazonSqsNotificationType(TypeEnum type = default(TypeEnum), string apiKeyRef = default(string), string apiSecretRef = default(string), string body = default(string), string queueUrlRef = default(string))
        {
            this.Type = type;
            // to ensure "apiKeyRef" is required (not null)
            if (apiKeyRef == null)
            {
                throw new ArgumentNullException("apiKeyRef is a required property for AmazonSqsNotificationType and cannot be null");
            }
            this.ApiKeyRef = apiKeyRef;
            // to ensure "apiSecretRef" is required (not null)
            if (apiSecretRef == null)
            {
                throw new ArgumentNullException("apiSecretRef is a required property for AmazonSqsNotificationType and cannot be null");
            }
            this.ApiSecretRef = apiSecretRef;
            // to ensure "body" is required (not null)
            if (body == null)
            {
                throw new ArgumentNullException("body is a required property for AmazonSqsNotificationType and cannot be null");
            }
            this.Body = body;
            // to ensure "queueUrlRef" is required (not null)
            if (queueUrlRef == null)
            {
                throw new ArgumentNullException("queueUrlRef is a required property for AmazonSqsNotificationType and cannot be null");
            }
            this.QueueUrlRef = queueUrlRef;
        }

        /// <summary>
        /// Reference to API key from Configuration Store
        /// </summary>
        /// <value>Reference to API key from Configuration Store</value>
        [DataMember(Name = "apiKeyRef", IsRequired = true, EmitDefaultValue = true)]
        public string ApiKeyRef { get; set; }

        /// <summary>
        /// Reference to API secret from Configuration Store
        /// </summary>
        /// <value>Reference to API secret from Configuration Store</value>
        [DataMember(Name = "apiSecretRef", IsRequired = true, EmitDefaultValue = true)]
        public string ApiSecretRef { get; set; }

        /// <summary>
        /// The body of the Amazon Queue Message
        /// </summary>
        /// <value>The body of the Amazon Queue Message</value>
        [DataMember(Name = "body", IsRequired = true, EmitDefaultValue = true)]
        public string Body { get; set; }

        /// <summary>
        /// Reference to queue url from Configuration Store
        /// </summary>
        /// <value>Reference to queue url from Configuration Store</value>
        [DataMember(Name = "queueUrlRef", IsRequired = true, EmitDefaultValue = true)]
        public string QueueUrlRef { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AmazonSqsNotificationType {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  ApiKeyRef: ").Append(ApiKeyRef).Append("\n");
            sb.Append("  ApiSecretRef: ").Append(ApiSecretRef).Append("\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  QueueUrlRef: ").Append(QueueUrlRef).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AmazonSqsNotificationType);
        }

        /// <summary>
        /// Returns true if AmazonSqsNotificationType instances are equal
        /// </summary>
        /// <param name="input">Instance of AmazonSqsNotificationType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AmazonSqsNotificationType input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                ) && 
                (
                    this.ApiKeyRef == input.ApiKeyRef ||
                    (this.ApiKeyRef != null &&
                    this.ApiKeyRef.Equals(input.ApiKeyRef))
                ) && 
                (
                    this.ApiSecretRef == input.ApiSecretRef ||
                    (this.ApiSecretRef != null &&
                    this.ApiSecretRef.Equals(input.ApiSecretRef))
                ) && 
                (
                    this.Body == input.Body ||
                    (this.Body != null &&
                    this.Body.Equals(input.Body))
                ) && 
                (
                    this.QueueUrlRef == input.QueueUrlRef ||
                    (this.QueueUrlRef != null &&
                    this.QueueUrlRef.Equals(input.QueueUrlRef))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Type.GetHashCode();
                if (this.ApiKeyRef != null)
                {
                    hashCode = (hashCode * 59) + this.ApiKeyRef.GetHashCode();
                }
                if (this.ApiSecretRef != null)
                {
                    hashCode = (hashCode * 59) + this.ApiSecretRef.GetHashCode();
                }
                if (this.Body != null)
                {
                    hashCode = (hashCode * 59) + this.Body.GetHashCode();
                }
                if (this.QueueUrlRef != null)
                {
                    hashCode = (hashCode * 59) + this.QueueUrlRef.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ApiKeyRef (string) minLength
            if (this.ApiKeyRef != null && this.ApiKeyRef.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ApiKeyRef, length must be greater than 1.", new [] { "ApiKeyRef" });
            }

            // ApiSecretRef (string) minLength
            if (this.ApiSecretRef != null && this.ApiSecretRef.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ApiSecretRef, length must be greater than 1.", new [] { "ApiSecretRef" });
            }

            // Body (string) maxLength
            if (this.Body != null && this.Body.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Body, length must be less than 1024.", new [] { "Body" });
            }

            // Body (string) minLength
            if (this.Body != null && this.Body.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Body, length must be greater than 1.", new [] { "Body" });
            }

            // Body (string) pattern
            Regex regexBody = new Regex(@"^[\s\S]*$", RegexOptions.CultureInvariant);
            if (false == regexBody.Match(this.Body).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Body, must match a pattern of " + regexBody, new [] { "Body" });
            }

            // QueueUrlRef (string) minLength
            if (this.QueueUrlRef != null && this.QueueUrlRef.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for QueueUrlRef, length must be greater than 1.", new [] { "QueueUrlRef" });
            }

            yield break;
        }
    }
}
